# Generated by Django 5.2.3 on 2026-01-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(help_text='Unique Identifier (e.g., Block/Plot number)', max_length=50, unique=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('zoning_type', models.CharField(blank=True, max_length=100, null=True)),
                ('geometry_json', models.TextField(help_text='GeoJSON Polygon coordinates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
