# Generated by Django 5.2.3 on 2026-01-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='address',
            new_name='zoning_info',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='size_sqm',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='zoning_type',
        ),
        migrations.AddField(
            model_name='parcel',
            name='adjacent_info',
            field=models.TextField(blank=True, help_text='Adjacent streets, landmarks, or neighbors', null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='centroid_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='centroid_lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='city',
            field=models.CharField(default='Addis Ababa', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=100),
        ),
        migrations.AddField(
            model_name='parcel',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Plot dimensions (e.g., 20m x 40m)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='entry_lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='entry_lng',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='has_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='has_sewage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='has_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='property_type',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('AGRICULTURAL', 'Agricultural')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='road_access',
            field=models.CharField(blank=True, choices=[('PAVED', 'Paved'), ('UNPAVED', 'Unpaved')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sub_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='title_deed_ref',
            field=models.CharField(blank=True, help_text='Title deed or registration reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='usage_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='wereda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='geometry_json',
            field=models.TextField(help_text='GeoJSON Polygon coordinates for boundaries'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='parcel_id',
            field=models.CharField(help_text='Official parcel ID / cadastral number', max_length=100, unique=True),
        ),
    ]
