# Generated by Django 5.2.3 on 2026-01-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_advanced_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
